// data.ts (updated)
import { Patient } from "./hooks/usePatients";

export interface PatientDataFile {
    fileId: string;
    fileUrl: string[];
    createdAt: Date;
    updatedAt: Date;
    recordCount: number;
    patients: Patient[];
}

export const data: PatientDataFile[] = [
    {
        fileId: "file-001",
        fileUrl: [
            "https://jsonplaceholder.typicode.com/users",
            "https://jsonplaceholder.typicode.com/posts"
        ],
        createdAt: new Date("2023-01-01"),
        updatedAt: new Date("2023-03-31"),
        recordCount: 20,
        patients: [
            {
                case: 1,
                patientName: "Theresia Mbah",
                sex: "F",
                age: 34,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Farmer",
                residence: "Bonaberi",
                contact: "688 854 144",
                history: "Yes",
                createdAt: new Date("2023-01-15")
            },
            {
                case: 2,
                patientName: "Peters Nze",
                sex: "M",
                age: 45,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Photographer",
                residence: "Bonaberi",
                contact: "677 123 456",
                history: "Yes",
                createdAt: new Date("2023-02-20")
            },
            {
                case: 3,
                patientName: "Ayissi Bi Paul",
                sex: "M",
                age: 28,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Teacher",
                residence: "Douala",
                contact: "699 234 567",
                history: "No",
                createdAt: new Date("2023-03-10")
            },
            {
                case: 4,
                patientName: "Ebeneza Ndoki",
                sex: "F",
                age: 29,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Business",
                residence: "Akwa",
                contact: "655 345 678",
                history: "Yes",
                createdAt: new Date("2023-01-22")
            },
            {
                case: 5,
                patientName: "Pierre Kwemo",
                sex: "M",
                age: 52,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Farmer",
                residence: "Bonaberi",
                contact: "677 456 789",
                history: "Yes",
                createdAt: new Date("2023-02-12")
            },
            {
                case: 6,
                patientName: "Chalefac Theodore",
                sex: "M",
                age: 38,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Driver",
                residence: "Makepe",
                contact: "688 567 890",
                history: "No",
                createdAt: new Date("2023-03-18")
            },
            {
                case: 7,
                patientName: "Kuma Theodore",
                sex: "M",
                age: 41,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Mechanic",
                residence: "Bonaberi",
                contact: "699 678 901",
                history: "No",
                createdAt: new Date("2023-01-25")
            },
            {
                case: 8,
                patientName: "Grace Njoh",
                sex: "F",
                age: 26,
                maritalStatus: "SI",
                isPregnant: 1,
                profession: "Nurse",
                residence: "Bonamoussadi",
                contact: "655 789 012",
                history: "No",
                createdAt: new Date("2023-02-14")
            },
            {
                case: 9,
                patientName: "Emmanuel Fru",
                sex: "M",
                age: 33,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Engineer",
                residence: "Bepanda",
                contact: "677 890 123",
                history: "Yes",
                createdAt: new Date("2023-03-03")
            },
            {
                case: 10,
                patientName: "Julienne Ekeme",
                sex: "F",
                age: 31,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "House wife",
                residence: "Logbaba",
                contact: "688 901 234",
                history: "No",
                createdAt: new Date("2023-01-21")
            },
            {
                case: 11,
                patientName: "Martin Tanyi",
                sex: "M",
                age: 47,
                maritalStatus: "WI",
                isPregnant: 0,
                profession: "Carpenter",
                residence: "New Bell",
                contact: "699 012 345",
                history: "Yes",
                createdAt: new Date("2023-02-08")
            },
            {
                case: 12,
                patientName: "Beatrice Kom",
                sex: "F",
                age: 23,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Student",
                residence: "Cite Sic",
                contact: "655 123 456",
                history: "No",
                createdAt: new Date("2023-03-16")
            },
            {
                case: 13,
                patientName: "Joseph Manga",
                sex: "M",
                age: 55,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Retired",
                residence: "Bonaberi",
                contact: "677 234 567",
                history: "Yes",
                createdAt: new Date("2023-01-11")
            },
            {
                case: 14,
                patientName: "Marie Fouda",
                sex: "F",
                age: 36,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Hairdresser",
                residence: "Deido",
                contact: "688 345 678",
                history: "No",
                createdAt: new Date("2023-02-19")
            },
            {
                case: 15,
                patientName: "Samuel Njie",
                sex: "M",
                age: 29,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "IT Specialist",
                residence: "Akwa",
                contact: "699 456 789",
                history: "No",
                createdAt: new Date("2023-03-07")
            },
            {
                case: 16,
                patientName: "Christine Abena",
                sex: "F",
                age: 27,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Accountant",
                residence: "Bonanjo",
                contact: "655 567 890",
                history: "Yes",
                createdAt: new Date("2023-01-23")
            },
            {
                case: 17,
                patientName: "David Ngwa",
                sex: "M",
                age: 42,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Taxi Driver",
                residence: "Makepe",
                contact: "677 678 901",
                history: "Yes",
                createdAt: new Date("2023-02-28")
            },
            {
                case: 18,
                patientName: "Florence Bih",
                sex: "F",
                age: 39,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Trader",
                residence: "Bonaberi",
                contact: "688 789 012",
                history: "No",
                createdAt: new Date("2023-03-14")
            },
            {
                case: 19,
                patientName: "Patrick Tabe",
                sex: "M",
                age: 24,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Student",
                residence: "Ndogpassi",
                contact: "699 890 123",
                history: "No",
                createdAt: new Date("2023-01-09")
            },
            {
                case: 20,
                patientName: "Angelique Essomba",
                sex: "F",
                age: 32,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Secretary",
                residence: "Bali",
                contact: "655 901 234",
                history: "Yes",
                createdAt: new Date("2023-02-27")
            }
        ]
    },
    {
        fileId: "file-002",
        fileUrl: [
            "https://jsonplaceholder.typicode.com/comments",
            "https://jsonplaceholder.typicode.com/albums"
        ],
        createdAt: new Date("2023-04-01"),
        updatedAt: new Date("2023-06-30"),
        recordCount: 20,
        patients: [
            {
                case: 21,
                patientName: "Roland Bikoi",
                sex: "M",
                age: 37,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Police Officer",
                residence: "Bonapriso",
                contact: "677 111 222",
                history: "No",
                createdAt: new Date("2023-04-05")
            },
            {
                case: 22,
                patientName: "Claudine Ngo",
                sex: "F",
                age: 30,
                maritalStatus: "SI",
                isPregnant: 1,
                profession: "Bank Teller",
                residence: "Akwa",
                contact: "688 222 333",
                history: "Yes",
                createdAt: new Date("2023-04-12")
            },
            {
                case: 23,
                patientName: "Thomas Ebale",
                sex: "M",
                age: 48,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Electrician",
                residence: "Bonaberi",
                contact: "699 333 444",
                history: "Yes",
                createdAt: new Date("2023-04-20")
            },
            {
                case: 24,
                patientName: "Sarah Muna",
                sex: "F",
                age: 25,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Sales Rep",
                residence: "Bonamoussadi",
                contact: "655 444 555",
                history: "No",
                createdAt: new Date("2023-05-03")
            },
            {
                case: 25,
                patientName: "Francis Kuo",
                sex: "M",
                age: 35,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Chef",
                residence: "Deido",
                contact: "677 555 666",
                history: "No",
                createdAt: new Date("2023-05-15")
            },
            {
                case: 26,
                patientName: "Henriette Simo",
                sex: "F",
                age: 41,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Pharmacist",
                residence: "Bonanjo",
                contact: "688 666 777",
                history: "Yes",
                createdAt: new Date("2023-05-22")
            },
            {
                case: 27,
                patientName: "Bernard Talla",
                sex: "M",
                age: 50,
                maritalStatus: "WI",
                isPregnant: 0,
                profession: "Security Guard",
                residence: "Makepe",
                contact: "699 777 888",
                history: "Yes",
                createdAt: new Date("2023-06-01")
            },
            {
                case: 28,
                patientName: "Nadege Foko",
                sex: "F",
                age: 28,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Teacher",
                residence: "Bepanda",
                contact: "655 888 999",
                history: "No",
                createdAt: new Date("2023-06-10")
            },
            {
                case: 29,
                patientName: "Eric Mbarga",
                sex: "M",
                age: 44,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Mason",
                residence: "Bonaberi",
                contact: "677 999 000",
                history: "Yes",
                createdAt: new Date("2023-06-18")
            },
            {
                case: 30,
                patientName: "Viviane Pokam",
                sex: "F",
                age: 33,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Journalist",
                residence: "Akwa",
                contact: "688 000 111",
                history: "No",
                createdAt: new Date("2023-06-25")
            },
            {
                case: 31,
                patientName: "Albert Tchoua",
                sex: "M",
                age: 39,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Plumber",
                residence: "New Bell",
                contact: "699 111 222",
                history: "No",
                createdAt: new Date("2023-04-08")
            },
            {
                case: 32,
                patientName: "Monique Bella",
                sex: "F",
                age: 27,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Designer",
                residence: "Bonapriso",
                contact: "655 222 333",
                history: "Yes",
                createdAt: new Date("2023-04-16")
            },
            {
                case: 33,
                patientName: "Jean-Paul Nkeng",
                sex: "M",
                age: 53,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Lawyer",
                residence: "Bonanjo",
                contact: "677 333 444",
                history: "Yes",
                createdAt: new Date("2023-05-05")
            },
            {
                case: 34,
                patientName: "Rosine Ndoumbe",
                sex: "F",
                age: 31,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Midwife",
                residence: "Logbaba",
                contact: "688 444 555",
                history: "No",
                createdAt: new Date("2023-05-18")
            },
            {
                case: 35,
                patientName: "Georges Mvondo",
                sex: "M",
                age: 46,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Fisherman",
                residence: "Youpwe",
                contact: "699 555 666",
                history: "Yes",
                createdAt: new Date("2023-05-28")
            },
            {
                case: 36,
                patientName: "Lydie Kamdem",
                sex: "F",
                age: 24,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Waitress",
                residence: "Deido",
                contact: "655 666 777",
                history: "No",
                createdAt: new Date("2023-06-05")
            },
            {
                case: 37,
                patientName: "Alexis Fouda",
                sex: "M",
                age: 36,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Welder",
                residence: "Bonaberi",
                contact: "677 777 888",
                history: "No",
                createdAt: new Date("2023-06-12")
            },
            {
                case: 38,
                patientName: "Patience Moukouri",
                sex: "F",
                age: 29,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Tailor",
                residence: "Makepe",
                contact: "688 888 999",
                history: "Yes",
                createdAt: new Date("2023-06-20")
            },
            {
                case: 39,
                patientName: "Herve Njoya",
                sex: "M",
                age: 40,
                maritalStatus: "WI",
                isPregnant: 0,
                profession: "Butcher",
                residence: "Ndogpassi",
                contact: "699 999 000",
                history: "Yes",
                createdAt: new Date("2023-06-27")
            },
            {
                case: 40,
                patientName: "Irene Mbassi",
                sex: "F",
                age: 35,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Civil Servant",
                residence: "Bali",
                contact: "655 000 111",
                history: "No",
                createdAt: new Date("2023-06-29")
            }
        ]
    }
];