import { Patient } from "./hooks/usePatients";

export interface PatientDataFile {
    id: string;
    fileId: string;
    fileUrl: string[];
    createdAt: Date;
    updatedAt: Date;
    address: string;
    facilityName: string;
    recordCount: number;
    submissionStatus: 'N/A' | 'pending' | 'confirmed' | 'progress'
    patients: Patient[];
    facility?: FacilityDetails;
    contactPersonnels?: ContactPersonnel[];
}



export interface FacilityDetails {
    facilityName: string;
    address: string;
    division: string;
    healthDistrict: string;
    municipality: string;
    phone: string;
    email: string;
    site: string;
}

export interface ContactPersonnel {
    firstName: string;
    lastName: string;
    role: string;
    tel1: string;
    tel2: string;
    institution: string;
    email: string;
    lastActivity: string;
}

interface Notification {
    title: string;
    date: string;
    content: string;
}

export const notification: Notification[] = [
    {
        title: 'Upcoming vaccination campaigns',
        date: 'oct 17',
        content: `Date: October 17\nThe Ministry notifies everyone about the upcoming vaccination campaigns that will take place across all health districts. Citizens are encouraged to participate and ensure their vaccination cards are updated.`,
    },
    {
        title: 'Pregnancy Kits Available',
        date: 'oct 18',
        content: `Date: October 18\nThe Ministry informs all health centers and the general public that pregnancy kits are now available in designated facilities. Kindly visit your nearest health center for assistance.`,
    },
    {
        title: 'National AIDS activities',
        date: 'oct 19',
        content: `Date: October 19\nThe Ministry announces the commencement of National AIDS awareness activities aimed at prevention, testing, and counseling. Everyone is invited to participate and spread awareness.`,
    },
    {
        title: 'Breast Cancer Month',
        date: 'oct 20',
        content: `Date: October 20\nThe Ministry reminds all citizens that October is Breast Cancer Awareness Month. Early detection saves lives—visit the nearest hospital for screening and education programs.`,
    },
];


export const contactPersonnels: ContactPersonnel[] = [
    {
        firstName: "Emmanuel",
        lastName: "Ngong",
        role: "Chief Medical Officer",
        tel1: "+237 677 543 210",
        institution: 'The Martins',
        tel2: "+237 699 102 334",
        email: "emmanuel.ngong@stmaryhealth.org",
        lastActivity: '2023-03-31',
    },
    {
        firstName: "Brenda",
        lastName: "Ewane",
        role: "Nursing Supervisor",
        institution: 'St. Bless',
        tel1: "+237 670 998 877",
        tel2: "+237 680 112 009",
        email: "b.ewane@bamendaregional.cm",
        lastActivity: 'Yesterday',
    }
];

const facility: FacilityDetails =
{
    facilityName: "St. Mary’s Health Center",
    address: "12 Independence Avenue, Buea",
    division: "Fako",
    healthDistrict: "Buea District",
    municipality: "Buea",
    phone: "+237 677 123 456",
    email: "stmaryhealthcenter@gmail.com",
    site: "www.stmaryhealth.org",
};



export const data: PatientDataFile[] = [
    {
        id: 'LTV0214',
        fileId: "file-001",
        fileUrl: [
            "https://images-cdn.ubuy.com.sa/68bf86ddb87fc146c50136e6-home-accent-furnishings-72-rustic-solid.jpg",
            "https://i5.walmartimages.com/asr/f966de1e-c7c1-4017-b290-d657f99dd3d4_1.14f6b9cd1aa9561752e0d138b0167e68.jpeg",
        ],
        createdAt: new Date("2023-01-01"),
        updatedAt: new Date("2023-03-31"),
        recordCount: 20,
        address: 'Grand hanga',
        facilityName: 'Mbingo Hospital',
        submissionStatus: 'confirmed',
        facility,
        contactPersonnels,
        patients: [
            {
                id: 'LTV0214',
                case: 1,
                patientName: "Theresia Mbah",
                sex: "F",
                age: 34,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Farmer",
                residence: "Bonaberi",
                contact: "688 854 144",
                patientCode: "PAT-001",
                history: "Has prior malaria infection.",
                symptoms: ["Fever", "Headache", "Fatigue"],
                diagnosisPrescribing: "Malaria treatment protocol",
                testsRequested: ["Malaria test", "Blood count"],
                confirmedResults: ["Malaria positive"],
                confirmatoryDiagnosis: "Confirmed Malaria",
                treatment: ["Artemether-Lumefantrine", "Paracetamol"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1001",
                referenceHospital: "Laquintinie Hospital",
                observations: "Responding well to treatment",
                createdAt: new Date("2023-01-15"),
                updatedAt: new Date("2023-01-18"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 2,
                patientName: "Peters Nze",
                sex: "M",
                age: 45,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Photographer",
                residence: "Bonaberi",
                contact: "677 123 456",
                patientCode: "PAT-002",
                history: "Chronic smoker, occasional cough",
                symptoms: ["Cough", "Shortness of breath"],
                diagnosisPrescribing: "Bronchitis treatment",
                testsRequested: ["Chest X-ray", "Sputum test"],
                confirmedResults: ["Mild Bronchitis"],
                confirmatoryDiagnosis: "Chronic Bronchitis",
                treatment: ["Amoxicillin", "Cough syrup"],
                careLevel: "Observation",
                receiptNumber: "REC-1002",
                referenceHospital: "Douala General Hospital",
                observations: "Advised to quit smoking",
                createdAt: new Date("2023-02-20"),
                updatedAt: new Date("2023-02-25"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 3,
                patientName: "Ayissi Bi Paul",
                sex: "M",
                age: 28,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Teacher",
                residence: "Douala",
                contact: "699 234 567",
                patientCode: "PAT-003",
                history: "Healthy individual",
                symptoms: ["Fever", "Chills"],
                diagnosisPrescribing: "Malaria suspected",
                testsRequested: ["Malaria test"],
                confirmedResults: ["Negative"],
                confirmatoryDiagnosis: "No malaria",
                treatment: ["Paracetamol"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1003",
                referenceHospital: "PolyClinic St. John",
                observations: "Recovered without complications",
                createdAt: new Date("2023-03-10"),
                updatedAt: new Date("2023-03-12"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 4,
                patientName: "Ebeneza Ndoki",
                sex: "F",
                age: 29,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Businesswoman",
                residence: "Akwa",
                contact: "655 345 678",
                patientCode: "PAT-004",
                history: "2 months pregnant, mild nausea",
                symptoms: ["Vomiting", "Dizziness"],
                diagnosisPrescribing: "Prenatal vitamins",
                testsRequested: ["Ultrasound", "Urine test"],
                confirmedResults: ["Normal pregnancy"],
                confirmatoryDiagnosis: "Healthy pregnancy",
                treatment: ["Prenatal vitamins", "Rest"],
                careLevel: "Observation",
                receiptNumber: "REC-1004",
                referenceHospital: "Akwa District Hospital",
                observations: "Stable condition",
                createdAt: new Date("2023-01-22"),
                updatedAt: new Date("2023-01-25"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 5,
                patientName: "Pierre Kwemo",
                sex: "M",
                age: 52,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Farmer",
                residence: "Bonaberi",
                contact: "677 456 789",
                patientCode: "PAT-005",
                history: "High blood pressure",
                symptoms: ["Headache", "Dizziness"],
                diagnosisPrescribing: "Hypertension management",
                testsRequested: ["Blood pressure test"],
                confirmedResults: ["BP: 160/100 mmHg"],
                confirmatoryDiagnosis: "Hypertension",
                treatment: ["Amlodipine", "Diet change"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1005",
                referenceHospital: "Douala General Hospital",
                observations: "Follow-up needed",
                createdAt: new Date("2023-02-12"),
                updatedAt: new Date("2023-02-15"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 6,
                patientName: "Chalefac Theodore",
                sex: "M",
                age: 38,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Driver",
                residence: "Makepe",
                contact: "688 567 890",
                patientCode: "PAT-006",
                history: "No",
                symptoms: ["Headache"],
                diagnosisPrescribing: "Headache relief",
                testsRequested: ["Blood pressure check"],
                confirmedResults: ["Normal"],
                confirmatoryDiagnosis: "Tension headache",
                treatment: ["Ibuprofen"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1006",
                referenceHospital: "Makepe Health Center",
                observations: "Mild headache, advised rest",
                createdAt: new Date("2023-03-18"),
                updatedAt: new Date("2023-03-20"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 7,
                patientName: "Kuma Theodore",
                sex: "M",
                age: 41,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Mechanic",
                residence: "Bonaberi",
                contact: "699 678 901",
                patientCode: "PAT-007",
                history: "No",
                symptoms: ["Back pain"],
                diagnosisPrescribing: "Pain relief",
                testsRequested: ["X-ray"],
                confirmedResults: ["Mild strain"],
                confirmatoryDiagnosis: "Muscle strain",
                treatment: ["Painkillers", "Rest"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1007",
                referenceHospital: "Bonaberi Clinic",
                observations: "Back strain from work, rest advised",
                createdAt: new Date("2023-01-25"),
                updatedAt: new Date("2023-01-27"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 8,
                patientName: "Grace Njoh",
                sex: "F",
                age: 26,
                maritalStatus: "SI",
                isPregnant: 1,
                profession: "Nurse",
                residence: "Bonamoussadi",
                contact: "655 789 012",
                patientCode: "PAT-008",
                history: "No",
                symptoms: ["Nausea", "Fatigue"],
                diagnosisPrescribing: "Prenatal care",
                testsRequested: ["Pregnancy test", "Ultrasound"],
                confirmedResults: ["Pregnant", "Normal"],
                confirmatoryDiagnosis: "Healthy pregnancy",
                treatment: ["Prenatal vitamins", "Rest"],
                careLevel: "Observation",
                receiptNumber: "REC-1008",
                referenceHospital: "Bonamoussadi Maternity",
                observations: "First trimester, stable",
                createdAt: new Date("2023-02-14"),
                updatedAt: new Date("2023-02-16"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 9,
                patientName: "Emmanuel Fru",
                sex: "M",
                age: 33,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Engineer",
                residence: "Akwa",
                contact: "677 890 123",
                patientCode: "PAT-009",
                history: "No prior illnesses",
                symptoms: ["Stomach pain", "Nausea"],
                diagnosisPrescribing: "Gastritis suspected",
                testsRequested: ["Ultrasound", "Stool test"],
                confirmedResults: ["Mild gastritis"],
                confirmatoryDiagnosis: "Acute Gastritis",
                treatment: ["Antacids", "Probiotics"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1009",
                referenceHospital: "Akwa District Hospital",
                observations: "Dietary advice given",
                createdAt: new Date("2023-01-30"),
                updatedAt: new Date("2023-02-02"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 10,
                patientName: "Julienne Ekeme",
                sex: "F",
                age: 31,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "House wife",
                residence: "Logbaba",
                contact: "688 901 234",
                patientCode: "PAT-010",
                history: "No",
                symptoms: ["Morning sickness", "Fatigue"],
                diagnosisPrescribing: "Prenatal care",
                testsRequested: ["Blood test", "Ultrasound"],
                confirmedResults: ["Normal pregnancy"],
                confirmatoryDiagnosis: "Healthy pregnancy",
                treatment: ["Folic acid", "Iron supplements"],
                careLevel: "Observation",
                receiptNumber: "REC-1010",
                referenceHospital: "Logbaba Maternity",
                observations: "First trimester, monitor blood pressure",
                createdAt: new Date("2023-01-21"),
                updatedAt: new Date("2023-01-24"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 11,
                patientName: "Martin Tanyi",
                sex: "M",
                age: 47,
                maritalStatus: "WI",
                isPregnant: 0,
                profession: "Carpenter",
                residence: "New Bell",
                contact: "699 012 345",
                patientCode: "PAT-011",
                history: "Yes",
                symptoms: ["Joint pain", "Swelling"],
                diagnosisPrescribing: "Arthritis management",
                testsRequested: ["X-ray", "Blood test"],
                confirmedResults: ["Osteoarthritis"],
                confirmatoryDiagnosis: "Chronic Arthritis",
                treatment: ["Pain relievers", "Physical therapy"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1011",
                referenceHospital: "New Bell Clinic",
                observations: "Recommend exercise and weight management",
                createdAt: new Date("2023-02-08"),
                updatedAt: new Date("2023-02-12"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 12,
                patientName: "Beatrice Kom",
                sex: "F",
                age: 23,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Student",
                residence: "Cite Sic",
                contact: "655 123 456",
                patientCode: "PAT-012",
                history: "No",
                symptoms: ["Headache", "Dizziness"],
                diagnosisPrescribing: "Migraine suspected",
                testsRequested: ["Neurological exam"],
                confirmedResults: ["Tension headache"],
                confirmatoryDiagnosis: "Migraine",
                treatment: ["Painkillers", "Rest"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1012",
                referenceHospital: "Cite Sic Health Center",
                observations: "Stress-related, advised relaxation",
                createdAt: new Date("2023-03-16"),
                updatedAt: new Date("2023-03-18"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 13,
                patientName: "Joseph Manga",
                sex: "M",
                age: 55,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Retired",
                residence: "Bonaberi",
                contact: "677 234 567",
                patientCode: "PAT-013",
                history: "Yes",
                symptoms: ["Chest pain", "Shortness of breath"],
                diagnosisPrescribing: "Cardiac evaluation",
                testsRequested: ["ECG", "Chest X-ray"],
                confirmedResults: ["Mild angina"],
                confirmatoryDiagnosis: "Coronary Artery Disease",
                treatment: ["Beta-blockers", "Lifestyle changes"],
                careLevel: "Observation",
                receiptNumber: "REC-1013",
                referenceHospital: "Bonaberi Cardiac Center",
                observations: "Monitor blood pressure, follow-up in 2 weeks",
                createdAt: new Date("2023-01-11"),
                updatedAt: new Date("2023-01-15"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 14,
                patientName: "Marie Fouda",
                sex: "F",
                age: 36,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Hairdresser",
                residence: "Deido",
                contact: "688 345 678",
                patientCode: "PAT-014",
                history: "No",
                symptoms: ["Skin rash", "Itching"],
                diagnosisPrescribing: "Allergic reaction",
                testsRequested: ["Skin test"],
                confirmedResults: ["Contact dermatitis"],
                confirmatoryDiagnosis: "Allergic Dermatitis",
                treatment: ["Antihistamines", "Topical cream"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1014",
                referenceHospital: "Deido Dermatology Clinic",
                observations: "Avoid chemical exposure, follow-up if worsens",
                createdAt: new Date("2023-02-19"),
                updatedAt: new Date("2023-02-22"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 15,
                patientName: "Samuel Njie",
                sex: "M",
                age: 29,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "IT Specialist",
                residence: "Akwa",
                contact: "699 456 789",
                patientCode: "PAT-015",
                history: "No",
                symptoms: ["Eye strain", "Headache"],
                diagnosisPrescribing: "Computer vision syndrome",
                testsRequested: ["Eye exam"],
                confirmedResults: ["Refractive error"],
                confirmatoryDiagnosis: "Myopia",
                treatment: ["Eyeglasses", "Screen breaks"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1015",
                referenceHospital: "Akwa Eye Clinic",
                observations: "Recommend 20-20-20 rule for screen time",
                createdAt: new Date("2023-03-07"),
                updatedAt: new Date("2023-03-10"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 16,
                patientName: "Christine Abena",
                sex: "F",
                age: 27,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Accountant",
                residence: "Bonanjo",
                contact: "655 567 890",
                patientCode: "PAT-016",
                history: "Yes",
                symptoms: ["Back pain", "Fatigue"],
                diagnosisPrescribing: "Prenatal back pain",
                testsRequested: ["Physical exam", "Ultrasound"],
                confirmedResults: ["Musculoskeletal strain"],
                confirmatoryDiagnosis: "Pregnancy-related back pain",
                treatment: ["Prenatal yoga", "Supportive belt"],
                careLevel: "Observation",
                receiptNumber: "REC-1016",
                referenceHospital: "Bonanjo Maternity",
                observations: "Second trimester, monitor posture",
                createdAt: new Date("2023-01-23"),
                updatedAt: new Date("2023-01-26"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 17,
                patientName: "David Ngwa",
                sex: "M",
                age: 42,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Taxi Driver",
                residence: "Makepe",
                contact: "677 678 901",
                patientCode: "PAT-017",
                history: "Yes",
                symptoms: ["Knee pain", "Swelling"],
                diagnosisPrescribing: "Joint injury",
                testsRequested: ["X-ray", "MRI"],
                confirmedResults: ["Meniscus tear"],
                confirmatoryDiagnosis: "Knee Injury",
                treatment: ["Rest", "Ice", "Physical therapy"],
                careLevel: "Observation",
                receiptNumber: "REC-1017",
                referenceHospital: "Makepe Orthopedic Clinic",
                observations: "Avoid driving long distances, follow-up in 1 week",
                createdAt: new Date("2023-02-28"),
                updatedAt: new Date("2023-03-03"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 18,
                patientName: "Florence Bih",
                sex: "F",
                age: 39,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Trader",
                residence: "Bonaberi",
                contact: "688 789 012",
                patientCode: "PAT-018",
                history: "No",
                symptoms: ["Abdominal pain", "Bloating"],
                diagnosisPrescribing: "Digestive disorder",
                testsRequested: ["Ultrasound", "Endoscopy"],
                confirmedResults: ["Irritable bowel syndrome"],
                confirmatoryDiagnosis: "IBS",
                treatment: ["Dietary changes", "Antispasmodics"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1018",
                referenceHospital: "Bonaberi Gastroenterology",
                observations: "Avoid trigger foods, stress management",
                createdAt: new Date("2023-03-14"),
                updatedAt: new Date("2023-03-17"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 19,
                patientName: "Patrick Tabe",
                sex: "M",
                age: 24,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Student",
                residence: "Ndogpassi",
                contact: "699 890 123",
                patientCode: "PAT-019",
                history: "No",
                symptoms: ["Fever", "Sore throat"],
                diagnosisPrescribing: "Viral infection",
                testsRequested: ["Throat swab", "Blood test"],
                confirmedResults: ["Streptococcal infection"],
                confirmatoryDiagnosis: "Strep Throat",
                treatment: ["Antibiotics", "Rest"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1019",
                referenceHospital: "Ndogpassi Health Center",
                observations: "Complete antibiotic course, isolate to prevent spread",
                createdAt: new Date("2023-01-09"),
                updatedAt: new Date("2023-01-12"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 20,
                patientName: "Angelique Essomba",
                sex: "F",
                age: 32,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Secretary",
                residence: "Bali",
                contact: "655 901 234",
                patientCode: "PAT-020",
                history: "Yes",
                symptoms: ["Swelling", "Fatigue"],
                diagnosisPrescribing: "Preeclampsia monitoring",
                testsRequested: ["Blood pressure", "Urine test"],
                confirmedResults: ["Proteinuria"],
                confirmatoryDiagnosis: "Preeclampsia",
                treatment: ["Bed rest", "Antihypertensives"],
                careLevel: "Hospitalization",
                receiptNumber: "REC-1020",
                referenceHospital: "Bali Maternity Hospital",
                observations: "High-risk pregnancy, daily monitoring required",
                createdAt: new Date("2023-02-27"),
                updatedAt: new Date("2023-03-02"),
                isRareCase: false,
                dataIssues: []
            }
        ]
    },
    {
        id: 'LTV0215',
        fileId: "file-002",
        fileUrl: [
            "https://images-cdn.ubuy.co.in/6523def57282053646118bd9-mhaosehu-industrial-coffee-table-for.jpg",
            "https://images.thdstatic.com/productImages/52238ccc-13d8-4ca9-8bc0-e4e678cadeeb/svn/silver-home-decorators-collection-coffee-tables-dc14-8445-64_1000.jpg"
        ],
        createdAt: new Date("2023-04-01"),
        updatedAt: new Date("2023-06-30"),
        recordCount: 20,
        address: 'Bonassama',
        facilityName: 'Bonassama Hospital',
        submissionStatus: 'progress',
        facility: {
            facilityName: "The Martins",
            address: "12 Independence Avenue, Buea",
            division: "Fako",
            healthDistrict: "Bamenda District",
            municipality: "Bamenda",
            phone: "+237 677 123 456",
            email: "stmaryhealthcenter@gmail.com",
            site: "www.stmaryhealth.org",
        },
        contactPersonnels,
        patients: [
            {
                id: 'LTV0214',
                case: 21,
                patientName: "Roland Bikoi",
                sex: "M",
                age: 37,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Police Officer",
                residence: "Bonapriso",
                contact: "677 111 222",
                patientCode: "PAT-021",
                history: "No chronic illness",
                symptoms: ["Cough", "Sore throat"],
                diagnosisPrescribing: "Flu management",
                testsRequested: ["Throat swab"],
                confirmedResults: ["Flu virus detected"],
                confirmatoryDiagnosis: "Influenza",
                treatment: ["Rest", "Vitamin C", "Paracetamol"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1021",
                referenceHospital: "Bonapriso Clinic",
                observations: "Condition improving",
                createdAt: new Date("2023-04-05"),
                updatedAt: new Date("2023-04-07"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 22,
                patientName: "Claudine Ngo",
                sex: "F",
                age: 30,
                maritalStatus: "SI",
                isPregnant: 1,
                profession: "Bank Teller",
                residence: "Akwa",
                contact: "688 222 333",
                patientCode: "PAT-022",
                history: "Yes",
                symptoms: ["Nausea", "Headache"],
                diagnosisPrescribing: "Prenatal check-up",
                testsRequested: ["Blood test", "Ultrasound"],
                confirmedResults: ["Normal"],
                confirmatoryDiagnosis: "Healthy pregnancy",
                treatment: ["Prenatal vitamins"],
                careLevel: "Observation",
                receiptNumber: "REC-1022",
                referenceHospital: "Akwa Maternity",
                observations: "Routine prenatal care",
                createdAt: new Date("2023-04-12"),
                updatedAt: new Date("2023-04-15"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 23,
                patientName: "Thomas Ebale",
                sex: "M",
                age: 48,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Electrician",
                residence: "Bonaberi",
                contact: "699 333 444",
                patientCode: "PAT-023",
                history: "Yes",
                symptoms: ["Back pain", "Fatigue"],
                diagnosisPrescribing: "Musculoskeletal pain",
                testsRequested: ["X-ray", "Physical exam"],
                confirmedResults: ["Herniated disc"],
                confirmatoryDiagnosis: "Lumbar Hernia",
                treatment: ["Pain medication", "Physical therapy"],
                careLevel: "Observation",
                receiptNumber: "REC-1023",
                referenceHospital: "Bonaberi Orthopedic",
                observations: "Avoid heavy lifting, follow-up in 2 weeks",
                createdAt: new Date("2023-04-20"),
                updatedAt: new Date("2023-04-23"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 24,
                patientName: "Sarah Muna",
                sex: "F",
                age: 25,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Sales Rep",
                residence: "Bonamoussadi",
                contact: "655 444 555",
                patientCode: "PAT-024",
                history: "No",
                symptoms: ["Cough", "Fever"],
                diagnosisPrescribing: "Respiratory infection",
                testsRequested: ["Chest X-ray", "Sputum culture"],
                confirmedResults: ["Pneumonia"],
                confirmatoryDiagnosis: "Bacterial Pneumonia",
                treatment: ["Antibiotics", "Cough syrup"],
                careLevel: "Observation",
                receiptNumber: "REC-1024",
                referenceHospital: "Bonamoussadi Hospital",
                observations: "Monitor oxygen levels, complete antibiotic course",
                createdAt: new Date("2023-05-03"),
                updatedAt: new Date("2023-05-08"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 25,
                patientName: "Francis Kuo",
                sex: "M",
                age: 35,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Chef",
                residence: "Deido",
                contact: "677 555 666",
                patientCode: "PAT-025",
                history: "No",
                symptoms: ["Burns", "Pain"],
                diagnosisPrescribing: "Burn treatment",
                testsRequested: ["Wound assessment"],
                confirmedResults: ["Second-degree burn"],
                confirmatoryDiagnosis: "Thermal Burn",
                treatment: ["Burn cream", "Pain relief"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1025",
                referenceHospital: "Deido Burn Center",
                observations: "Keep wound clean, change dressing daily",
                createdAt: new Date("2023-05-15"),
                updatedAt: new Date("2023-05-18"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 26,
                patientName: "Henriette Simo",
                sex: "F",
                age: 41,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Pharmacist",
                residence: "Bonanjo",
                contact: "688 666 777",
                patientCode: "PAT-026",
                history: "Yes",
                symptoms: ["Insomnia", "Anxiety"],
                diagnosisPrescribing: "Mental health evaluation",
                testsRequested: ["Psychological assessment"],
                confirmedResults: ["Mild depression"],
                confirmatoryDiagnosis: "Depressive Disorder",
                treatment: ["Counseling", "Antidepressants"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1026",
                referenceHospital: "Bonanjo Mental Health Clinic",
                observations: "Refer to psychiatrist, monitor medication effects",
                createdAt: new Date("2023-05-22"),
                updatedAt: new Date("2023-05-25"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 27,
                patientName: "Bernard Talla",
                sex: "M",
                age: 50,
                maritalStatus: "WI",
                isPregnant: 0,
                profession: "Security Guard",
                residence: "Makepe",
                contact: "699 777 888",
                patientCode: "PAT-027",
                history: "Yes",
                symptoms: ["High blood pressure", "Headache"],
                diagnosisPrescribing: "Hypertension follow-up",
                testsRequested: ["Blood pressure monitoring"],
                confirmedResults: ["BP: 170/110 mmHg"],
                confirmatoryDiagnosis: "Severe Hypertension",
                treatment: ["ACE inhibitors", "Dietary changes"],
                careLevel: "Observation",
                receiptNumber: "REC-1027",
                referenceHospital: "Makepe Cardiac Clinic",
                observations: "Emergency medication adjustment, daily BP checks",
                createdAt: new Date("2023-06-01"),
                updatedAt: new Date("2023-06-04"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 28,
                patientName: "Nadege Foko",
                sex: "F",
                age: 28,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Teacher",
                residence: "Bepanda",
                contact: "655 888 999",
                patientCode: "PAT-028",
                history: "No",
                symptoms: ["Vomiting", "Dehydration"],
                diagnosisPrescribing: "Hyperemesis gravidarum",
                testsRequested: ["Blood electrolytes", "Ultrasound"],
                confirmedResults: ["Electrolyte imbalance"],
                confirmatoryDiagnosis: "Severe Morning Sickness",
                treatment: ["IV fluids", "Antiemetics"],
                careLevel: "Hospitalization",
                receiptNumber: "REC-1028",
                referenceHospital: "Bepanda Maternity Hospital",
                observations: "Monitor fluid intake, nutritional support",
                createdAt: new Date("2023-06-10"),
                updatedAt: new Date("2023-06-13"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 29,
                patientName: "Eric Mbarga",
                sex: "M",
                age: 44,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Mason",
                residence: "Bonaberi",
                contact: "677 999 000",
                patientCode: "PAT-029",
                history: "Yes",
                symptoms: ["Fracture", "Pain"],
                diagnosisPrescribing: "Bone fracture",
                testsRequested: ["X-ray", "CT scan"],
                confirmedResults: ["Compound fracture"],
                confirmatoryDiagnosis: "Open Fracture",
                treatment: ["Surgery", "Immobilization"],
                careLevel: "Hospitalization",
                receiptNumber: "REC-1029",
                referenceHospital: "Bonaberi Trauma Center",
                observations: "Surgical intervention required, monitor for infection",
                createdAt: new Date("2023-06-18"),
                updatedAt: new Date("2023-06-21"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 30,
                patientName: "Viviane Pokam",
                sex: "F",
                age: 33,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Journalist",
                residence: "Akwa",
                contact: "688 000 111",
                patientCode: "PAT-030",
                history: "No",
                symptoms: ["Fatigue", "Swelling"],
                diagnosisPrescribing: "Prenatal monitoring",
                testsRequested: ["Blood pressure", "Ultrasound"],
                confirmedResults: ["Gestational hypertension"],
                confirmatoryDiagnosis: "Pregnancy-Induced Hypertension",
                treatment: ["Rest", "Blood pressure medication"],
                careLevel: "Observation",
                receiptNumber: "REC-1030",
                referenceHospital: "Akwa Maternity Clinic",
                observations: "Third trimester, close monitoring required",
                createdAt: new Date("2023-06-25"),
                updatedAt: new Date("2023-06-28"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 31,
                patientName: "Albert Tchoua",
                sex: "M",
                age: 39,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Plumber",
                residence: "New Bell",
                contact: "699 111 222",
                patientCode: "PAT-031",
                history: "No",
                symptoms: ["Diarrhea", "Abdominal cramps"],
                diagnosisPrescribing: "Gastroenteritis",
                testsRequested: ["Stool culture", "Blood test"],
                confirmedResults: ["Bacterial gastroenteritis"],
                confirmatoryDiagnosis: "Acute Gastroenteritis",
                treatment: ["Oral rehydration", "Antibiotics"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1031",
                referenceHospital: "New Bell Health Center",
                observations: "Hydration status monitored, avoid contaminated food",
                createdAt: new Date("2023-04-08"),
                updatedAt: new Date("2023-04-11"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 32,
                patientName: "Monique Bella",
                sex: "F",
                age: 27,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Designer",
                residence: "Bonapriso",
                contact: "655 222 333",
                patientCode: "PAT-032",
                history: "Yes",
                symptoms: ["Allergic reaction", "Hives"],
                diagnosisPrescribing: "Allergy management",
                testsRequested: ["Allergy test", "Skin prick test"],
                confirmedResults: ["Food allergy"],
                confirmatoryDiagnosis: "Food Allergy",
                treatment: ["Antihistamines", "Epinephrine auto-injector"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1032",
                referenceHospital: "Bonapriso Allergy Clinic",
                observations: "Avoid allergens, carry emergency medication",
                createdAt: new Date("2023-04-16"),
                updatedAt: new Date("2023-04-19"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 33,
                patientName: "Jean-Paul Nkeng",
                sex: "M",
                age: 53,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Lawyer",
                residence: "Bonanjo",
                contact: "677 333 444",
                patientCode: "PAT-033",
                history: "Yes",
                symptoms: ["Chest tightness", "Palpitations"],
                diagnosisPrescribing: "Cardiac arrhythmia",
                testsRequested: ["ECG", "Holter monitor"],
                confirmedResults: ["Atrial fibrillation"],
                confirmatoryDiagnosis: "Atrial Fibrillation",
                treatment: ["Anticoagulants", "Beta-blockers"],
                careLevel: "Observation",
                receiptNumber: "REC-1033",
                referenceHospital: "Bonanjo Cardiac Center",
                observations: "Monitor heart rate, anticoagulation therapy initiated",
                createdAt: new Date("2023-05-05"),
                updatedAt: new Date("2023-05-08"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 34,
                patientName: "Rosine Ndoumbe",
                sex: "F",
                age: 31,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Midwife",
                residence: "Logbaba",
                contact: "688 444 555",
                patientCode: "PAT-034",
                history: "No",
                symptoms: ["Contractions", "Water breaking"],
                diagnosisPrescribing: "Labor induction",
                testsRequested: ["Cervical exam", "Fetal monitoring"],
                confirmedResults: ["Full dilation"],
                confirmatoryDiagnosis: "Active Labor",
                treatment: ["Epidural", "Oxytocin"],
                careLevel: "Hospitalization",
                receiptNumber: "REC-1034",
                referenceHospital: "Logbaba Maternity Hospital",
                observations: "Second stage of labor, monitor fetal heart rate",
                createdAt: new Date("2023-05-18"),
                updatedAt: new Date("2023-05-21"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 35,
                patientName: "Georges Mvondo",
                sex: "M",
                age: 46,
                maritalStatus: "DI",
                isPregnant: 0,
                profession: "Fisherman",
                residence: "Youpwe",
                contact: "699 555 666",
                patientCode: "PAT-035",
                history: "Yes",
                symptoms: ["Seasickness", "Dizziness"],
                diagnosisPrescribing: "Motion sickness",
                testsRequested: ["Balance test"],
                confirmedResults: ["Vestibular dysfunction"],
                confirmatoryDiagnosis: "Motion Sickness",
                treatment: ["Antiemetics", "Vestibular rehabilitation"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1035",
                referenceHospital: "Youpwe ENT Clinic",
                observations: "Avoid rough seas, gradual exposure therapy",
                createdAt: new Date("2023-05-28"),
                updatedAt: new Date("2023-05-31"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 36,
                patientName: "Lydie Kamdem",
                sex: "F",
                age: 24,
                maritalStatus: "SI",
                isPregnant: 0,
                profession: "Waitress",
                residence: "Deido",
                contact: "655 666 777",
                patientCode: "PAT-036",
                history: "No",
                symptoms: ["Back pain", "Fatigue"],
                diagnosisPrescribing: "Musculoskeletal pain",
                testsRequested: ["Physical exam", "X-ray"],
                confirmedResults: ["Muscle strain"],
                confirmatoryDiagnosis: "Back Strain",
                treatment: ["Pain relievers", "Rest"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1036",
                referenceHospital: "Deido Health Center",
                observations: "Work-related strain, advise ergonomic changes",
                createdAt: new Date("2023-06-05"),
                updatedAt: new Date("2023-06-08"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 37,
                patientName: "Alexis Fouda",
                sex: "M",
                age: 36,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Welder",
                residence: "Bonaberi",
                contact: "677 777 888",
                patientCode: "PAT-037",
                history: "No",
                symptoms: ["Burn injury", "Pain"],
                diagnosisPrescribing: "Burn treatment",
                testsRequested: ["Wound assessment"],
                confirmedResults: ["First-degree burn"],
                confirmatoryDiagnosis: "Thermal Burn",
                treatment: ["Burn ointment", "Pain relief"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1037",
                referenceHospital: "Bonaberi Burn Unit",
                observations: "Protect from infection, monitor healing",
                createdAt: new Date("2023-06-12"),
                updatedAt: new Date("2023-06-15"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 38,
                patientName: "Patience Moukouri",
                sex: "F",
                age: 29,
                maritalStatus: "MA",
                isPregnant: 1,
                profession: "Tailor",
                residence: "Makepe",
                contact: "688 888 999",
                patientCode: "PAT-038",
                history: "Yes",
                symptoms: ["Back pain", "Swelling"],
                diagnosisPrescribing: "Prenatal back pain",
                testsRequested: ["Physical exam", "Ultrasound"],
                confirmedResults: ["Musculoskeletal strain"],
                confirmatoryDiagnosis: "Pregnancy-related back pain",
                treatment: ["Prenatal massage", "Supportive belt"],
                careLevel: "Observation",
                receiptNumber: "REC-1038",
                referenceHospital: "Makepe Maternity",
                observations: "Second trimester, monitor posture",
                createdAt: new Date("2023-06-20"),
                updatedAt: new Date("2023-06-23"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 39,
                patientName: "Herve Njoya",
                sex: "M",
                age: 40,
                maritalStatus: "WI",
                isPregnant: 0,
                profession: "Butcher",
                residence: "Ndogpassi",
                contact: "699 999 000",
                patientCode: "PAT-039",
                history: "Yes",
                symptoms: ["Joint pain", "Swelling"],
                diagnosisPrescribing: "Arthritis management",
                testsRequested: ["X-ray", "Blood test"],
                confirmedResults: ["Osteoarthritis"],
                confirmatoryDiagnosis: "Chronic Arthritis",
                treatment: ["Pain relievers", "Physical therapy"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1039",
                referenceHospital: "Ndogpassi Clinic",
                observations: "Recommend exercise and weight management",
                createdAt: new Date("2023-06-27"),
                updatedAt: new Date("2023-06-30"),
                isRareCase: false,
                dataIssues: []
            },
            {
                id: 'LTV0214',
                case: 40,
                patientName: "Irene Mbassi",
                sex: "F",
                age: 35,
                maritalStatus: "MA",
                isPregnant: 0,
                profession: "Civil Servant",
                residence: "Bali",
                contact: "655 000 111",
                patientCode: "PAT-040",
                history: "No",
                symptoms: ["Headache", "Fatigue"],
                diagnosisPrescribing: "Migraine management",
                testsRequested: ["Neurological exam", "MRI"],
                confirmedResults: ["Chronic migraine"],
                confirmatoryDiagnosis: "Migraine",
                treatment: ["Triptans", "Preventive medication"],
                careLevel: "Ambulatory",
                receiptNumber: "REC-1040",
                referenceHospital: "Bali General Hospital",
                observations: "Stress-related, advise work-life balance",
                createdAt: new Date("2023-06-29"),
                updatedAt: new Date("2023-07-02"),
                isRareCase: false,
                dataIssues: []
            }
        ]
    }
];